name: CI with Docker

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:latest
        options: >-
          --privileged
          --name docker
          --detach

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and run Docker Compose
        run: |
          docker-compose up --build --abort-on-container-exit
